unit BCCommon.Images;

interface

uses
  System.SysUtils, System.Classes, Vcl.ImgList, Vcl.Controls, BCControls.ImageList;

const
  { Sql editor output }
  IMAGE_INDEX_FIND_IN_FILES = 82;
  IMAGE_INDEX_ERRORS = 170;
  IMAGE_INDEX_GRID = 195;
  IMAGE_INDEX_OUTPUT = 65;
  IMAGE_INDEX_PLAN = 145;
  { Main }
  IMAGE_INDEX_DBMS_OUTPUT_UP = 57;
  IMAGE_INDEX_DBMS_OUTPUT_DOWN = 56;
  IMAGE_INDEX_REFRESH = 161;
  IMAGE_INDEX_SCHEMA_BROWSER = 44;
  IMAGE_INDEX_SQL_EDITOR = 67;
  IMAGE_INDEX_SQL_HISTORY = 28;

  IMAGE_INDEX_RECORD = 158;
  IMAGE_INDEX_PAUSE = 143;

    { Image indexes }
  IMG_IDX_ROOT_ENABLED = 44;

  IMG_IDX_TABLE_ROOT = 198;
  IMG_IDX_TABLE_CHILD = 195;
  IMG_IDX_VIEW_ROOT = 232;
  IMG_IDX_VIEW_CHILD = 230;
  IMG_IDX_FUNCTION_ROOT = 94;
  IMG_IDX_FUNCTION_CHILD = 92;
  IMG_IDX_PROCEDURE_ROOT = 154;
  IMG_IDX_PROCEDURE_CHILD = 152;
  IMG_IDX_PACKAGE_ROOT = 139;
  IMG_IDX_PACKAGE_CHILD = 137;
  IMG_IDX_TRIGGER_ROOT = 220;
  IMG_IDX_TRIGGER_CHILD = 218;
  IMG_IDX_CONSTRAINT_ROOT = 36;
  IMG_IDX_CONSTRAINT_CHILD = 34;
  IMG_IDX_INDEX_ROOT = 104;
  IMG_IDX_INDEX_CHILD = 102;
  IMG_IDX_SEQUENCE_ROOT = 175;
  IMG_IDX_SEQUENCE_CHILD = 173;
  IMG_IDX_SYNONYM_ROOT = 189;
  IMG_IDX_SYNONYM_CHILD = 187;
  IMG_IDX_DBLINK_ROOT = 122;
  IMG_IDX_DBLINK_CHILD = 120;

  IMG_IDX_INVALID_OBJECT_ROOT = 42;
  IMG_IDX_INVALID_OBJECT_CHILD = 41;
  IMG_IDX_RECYCLE_BIN_ROOT = 8;
  IMG_IDX_RECYCLE_BIN_CHILD = 7;
  IMG_IDX_PRIMARY_KEY = 114;
  IMG_IDX_FOREIGN_KEY = 113;
  IMG_IDX_FILTER_ADD = 79;
  IMG_IDX_FILTER_EDIT = 80;
  IMG_IDX_ALTER_TABLE = 200;
  IMG_IDX_RENAME = 208;
  IMG_IDX_COMPILE_ALL = 32;
  IMG_IDX_COMPILE = 33;
  IMG_IDX_FLASHBACK = 159;
  IMG_IDX_PURGE = 6;
  IMG_IDX_ANALYZE_TABLE = 26;
  IMG_IDX_ENABLE = 210;
  IMG_IDX_DISABLE = 62;
  IMG_IDX_USER_ROOT = 229;
  IMG_IDX_USER_CHILD = 228;
  IMG_IDX_LOCKED = 125;
  IMG_IDX_EXPIRED_AND_LOCKED = 126;
  IMG_IDX_TABLE_DROP = 199;
  IMG_IDX_VIEW_DROP = 233;
  IMG_IDX_FUNCTION_DROP = 95;
  IMG_IDX_PROCEDURE_DROP = 155;
  IMG_IDX_PACKAGE_DROP = 140;
  IMG_IDX_TRIGGER_DROP = 221;
  IMG_IDX_CONSTRAINT_DROP = 37;
  IMG_IDX_INDEX_DROP = 105;
  IMG_IDX_SEQUENCE_DROP = 176;
  IMG_IDX_SYNONYM_DROP = 176;
  IMG_IDX_DBLINK_DROP = 123;
  IMG_IDX_USER_DROP = 226;
  IMG_IDX_TABLE_CREATE = 196;
  IMG_IDX_VIEW_CREATE = 231;
  IMG_IDX_FUNCTION_CREATE = 93;
  IMG_IDX_PROCEDURE_CREATE = 153;
  IMG_IDX_PACKAGE_CREATE = 138;
  IMG_IDX_TRIGGER_CREATE = 219;
  IMG_IDX_CONSTRAINT_CREATE = 35;
  IMG_IDX_INDEX_CREATE = 103;
  IMG_IDX_SEQUENCE_CREATE = 174;
  IMG_IDX_SYNONYM_CREATE = 188;
  IMG_IDX_DBLINK_CREATE = 121;
  IMG_IDX_USER_CREATE = 225;
  IMG_IDX_CUSTOMIZE = 136;
  IMG_IDX_ALTER_VIEW = 234;

  IMG_IDX_KEY = 110;
  IMG_IDX_SQL_SCRIPT = 67;

  IMG_IDX_COMMENT = 246;
  IMG_IDX_TABLE_COLUMN = 197;

  IMG_IDX_FUNCTION = 239;
  IMG_IDX_PROCEDURE = 240;
  IMG_IDX_CONSTANT = 241;
  IMG_IDX_EXCEPTION = 242;
  IMG_IDX_TYPE = 243;
  IMG_IDX_CURSOR = 244;
  IMG_IDX_VARIABLE = 245;

  IMG_IDX_UNIQUE_KEY = 115;
  IMG_IDX_CHECK = 209;

  IMG_IDX_ADD = 0;

  IMG_IDX_TABLE_INVALID = 203;
  IMG_IDX_VIEW_INVALID = 235;
  IMG_IDX_FUNCTION_INVALID = 96;
  IMG_IDX_PROCEDURE_INVALID = 156;
  IMG_IDX_PACKAGE_INVALID = 141;
  IMG_IDX_TRIGGER_INVALID = 222;
  IMG_IDX_CONSTRAINT_INVALID = 38;
  IMG_IDX_INDEX_INVALID = 106;
  IMG_IDX_SEQUENCE_INVALID = 177;
  IMG_IDX_SYNONYM_INVALID = 191;
  IMG_IDX_DBLINK_INVALID = 124;

type
  TImagesDataModule = class(TDataModule)
    ImageList: TBCImageList;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  ImagesDataModule: TImagesDataModule;

implementation

uses
  Forms;

{%CLASSGROUP 'Vcl.Controls.TControl'}

{$R *.dfm}

initialization

  Application.CreateForm(TImagesDataModule, ImagesDataModule);

end.
