unit XMLConstants;

interface

const
  XML_BETWEEN_CONDITION = 'Between';
  XML_BETWEEN_UPPERBOUND = 'UpperBound';
  XML_BOOLEAN_EXPRESSION = 'BooleanExpression';
  XML_BRACKET_QUOTED_NAME = 'BracketQuotedName';
  XML_COMMENT_MULTILINE = 'MultiLineComment';
  XML_COMMENT_SINGLELINE = 'SingleLineComment';
  XML_COMPOUNDKEYWORD = 'CompoundKeyword';
  XML_CONTAINER_GENERALCONTENT = 'ContainerContentBody';
  XML_CONTAINER_OPEN = 'ContainerOpen';
  XML_CONTAINER_SINGLESTATEMENT = 'ContainerSingleStatementBody';
  XML_CTE_ALIAS = 'CTEAlias';
  XML_CTE_AS_BLOCK = 'CTEAsBlock';
  XML_CTE_WITH_CLAUSE = 'CTEWithClause';
  XML_CURSOR_DECLARATION = 'CursorDeclaration';
  XML_CURSOR_FOR_BLOCK = 'CursorForBlock';
  XML_CURSOR_FOR_OPTIONS = 'CursorForOptions';
  XML_DATATYPE_KEYWORD = 'DataTypeKeyword';
  XML_DDL_DECLARE_BLOCK = 'DDLDeclareBlock';
  XML_DDL_OTHER_BLOCK = 'DDLOtherBlock';
  XML_DDL_PARENS = 'DDLParens';
  XML_DDL_PROCEDURAL_BLOCK = 'DDLProceduralBlock';
  XML_DDL_WITH_CLAUSE = 'DDLWith';
  XML_DDLDETAIL_PARENS = 'DDLDetailParens';
  XML_ELSE_CLAUSE = 'ElseClause';
  XML_ERRORFOUND = 'ErrorFound';
  XML_EXPRESSION_PARENS = 'ExpressionParens';
  XML_FUNCTION_KEYWORD = 'FunctionKeyword';
  XML_FUNCTION_PARENS = 'FunctionParens';
  XML_HASERROR = 'HasError';
  XML_IF_STATEMENT = 'IfStatement';
  XML_JOIN_ON_SECTION = 'JoinOn';
  XML_MERGE_ACTION = 'MergeAction';
  XML_MERGE_WHEN = 'MergeWhen';
  XML_OTHERKEYWORD = 'OtherKeyword';
  XML_OTHERNODE = 'Other';
  XML_PERMISSIONS_BLOCK = 'PermissionsBlock';
  XML_PERMISSIONS_DETAIL = 'PermissionsDetail';
  XML_PERMISSIONS_RECIPIENT = 'PermissionsRecipient';
  XML_PERMISSIONS_TARGET = 'PermissionsTarget';
  XML_SELECTIONTARGET = 'SelectionTarget';
  XML_SELECTIONTARGET_PARENS = 'SelectionTargetParens';
  XML_SET_OPERATOR_CLAUSE = 'SetOperatorClause';
  XML_SIMPLETEXT = 'SimpleText';
  XML_SQL_CLAUSE = 'SQLClause';
  XML_SQL_ROOT = 'SQLRoot';
  XML_SQL_STATEMENT = 'SQLStatement';
  XML_TRIGGER_CONDITION = 'TriggerCondition';
  XML_WHILE_LOOP = 'WhileLoop';
  XML_WHITESPACE = 'WhiteSpace';
  XML_STRING = 'String';
  XML_NSTRING = 'NationalString';
  XML_QUOTED_STRING = 'QuotedString';
  XML_COMMA = 'Comma';
  XML_PERIOD = 'Period';
  XML_SEMICOLON = 'Semicolon';
  XML_ASTERISK = 'Asterisk';
  XML_OTHEROPERATOR = 'OtherOperator';
  XML_NUMBER_VALUE = 'NumberValue';
  XML_MONETARY_VALUE = 'MonetaryValue';
  XML_BINARY_VALUE = 'BinaryValue';
  XML_PSEUDONAME = 'PseudoName';
  XML_DDL_RETURNS = 'DDLReturns';
  XML_DDL_AS_BLOCK = 'DDLAsBlock';
  XML_BEGIN_TRANSACTION = 'BeginTransaction';
  XML_SAVE_TRANSACTION = 'SaveTransaction';
  XML_COMMIT_TRANSACTION = 'CommitTransaction';
  XML_ROLLBACK_TRANSACTION = 'RollbackTransaction';
  XML_TRY_BLOCK = 'TryBlock';
  XML_CONTAINER_MULTISTATEMENT = 'ContainerMultiStatementBody';
  XML_CATCH_BLOCK = 'CatchBlock';
  XML_BEGIN_END_BLOCK = 'BeginEndBlock';
  XML_MERGE_CLAUSE = 'MergeClause';
  XML_MERGE_TARGET = 'MergeTarget';
  XML_MERGE_USING = 'MergeUsing';
  XML_MERGE_CONDITION = 'MergeCondition';
  XML_CASE_STATEMENT = 'CaseStatement';
  XML_CASE_INPUT = 'Input';
  XML_CASE_THEN = 'Then';
  XML_CASE_WHEN = 'When';
  XML_MERGE_THEN = 'MergeThen';
  XML_CONTAINER_CLOSE = 'ContainerClose';
  XML_CASE_ELSE = 'CaseElse';
  XML_BATCH_SEPARATOR = 'BatchSeparator';
  XML_BETWEEN_LOWERBOUND = 'LowerBound';
  XML_AND_OPERATOR = 'And';
  XML_OR_OPERATOR = 'Or';
  XML_LABEL = 'Label';
  XML_ALPHAOPERATOR = 'AlphaOperator';
  XML_SCOPERESOLUTIONOPERATOR = 'ScopeResolutionOperator';
  XML_EQUALSSIGN = 'EqualsSign';

  PARSING_ERRORS_FOUND = '// Parsing errors found.';

implementation

end.
